---
- name: Converge - Uninstall
  hosts: all
  gather_facts: yes
  become: yes
  vars:
    ansible_become_method: runas
    ansible_become_user: ansible
    state: absent
  tasks:
    - name: "Include docker - state = absent (no-Windows)"
      ansible.builtin.include_role:
        name: "docker"
      when: ansible_os_family != "Windows"

    - name: "Include docker - state = absent (Windows)"
      ansible.builtin.include_role:
        name: "docker"
      when: ansible_os_family == "Windows"
