---
- name: Converge - Uninstall (ssh)
  hosts: ssh
  gather_facts: yes
  become: yes
  vars:
    state: absent
  tasks:
    - name: "Include docker - state = absent (no-Windows)"
      ansible.builtin.include_role:
        name: "docker"

- name: Converge - Uninstall (winrm)
  hosts: winrm
  connection: psrp
  gather_facts: yes
  become: yes
  vars:
    ansible_port: 5985
    ansible_winrm_transport: basic
    ansible_winrm_read_timeout_sec: 120
    ansible_winrm_operation_timeout_sec: 90
    ansible_become_method: runas
    ansible_become_user: ansible
    ansible_winrm_server_cert_validation: ignore
    ansible_psrp_connection_timeout: 120
    ansible_psrp_operation_timeout: 90
    ansible_psrp_read_timeout: 120
    ansible_psrp_reconnection_retries: 10
    state: absent
  tasks:
    - name: "Include docker - state = absent (Windows)"
      ansible.builtin.include_role:
        name: "docker"
