---
# This is an example playbook to execute Ansible tests.

- name: Verify (ssh)
  hosts: ssh
  gather_facts: false
  tasks:
    - name: Do hello-world
      ansible.builtin.command: docker run hello-world
      become: yes
      register: result
      failed_when: false

    - assert:
        that:
          - result.rc == 2

- name: Verify (winrm)
  hosts: winrm
  vars:
    ansible_become_method: runas
    ansible_become_user: ansible
  gather_facts: false
  tasks:
    - name: Do hello-world
      ansible.windows.win_shell: docker run hello-world
      become: yes
      register: result
      failed_when: false

    - assert:
        that:
          - result.rc == 2

