---
- name: Converge - Install (ssh)
  hosts: ssh
  gather_facts: yes
  become: yes
  tasks:
    - name: "Include docker - state = present"
      ansible.builtin.include_role:
        name: "docker"

- name: Converge - Install (winrm)
  hosts: winrm
  connection: psrp
  gather_facts: yes
  become: yes
  vars:
    ansible_port: 5985
    ansible_winrm_transport: basic
    ansible_become_method: runas
    ansible_become_user: ansible
    ansible_winrm_server_cert_validation: ignore
  tasks:
#    - name: Gather facts
#      ansible.builtin.setup:
#        gather_subset:
#          - machine
#          - lsb
#          - kernel

    - name: "Include docker - state = present"
      ansible.builtin.include_role:
        name: "docker"