---
- name: Converge - Install (ssh)
  hosts: ssh
  gather_facts: yes
  become: yes
  tasks:
    - name: "Include docker - state = present"
      ansible.builtin.include_role:
        name: "docker"

- name: Converge - Install (winrm)
  hosts: winrm
  connection: psrp
  gather_facts: yes
  become: yes
  vars:
    ansible_port: 5985
    ansible_winrm_transport: basic
    ansible_become_method: runas
    ansible_become_user: ansible
    ansible_winrm_server_cert_validation: ignore
    ansible_psrp_connection_timeout: 60
    ansible_psrp_reconnection_retries: 10
  tasks:
    - name: "Include docker - state = present"
      ansible.builtin.include_role:
        name: "docker"