---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: yes
  tasks:
    - name: Do hello-world (no-Windows)
      ansible.builtin.command: docker run hello-world
      become: yes
      register: result
      retries: 5
      delay: 5
      until: result.rc == 0
      when: ansible_os_family != "Windows"

    - name: Do hello-world (Windows)
      ansible.windows.win_shell: docker run hello-world
      register: result
      retries: 5
      delay: 5
      until: result.rc == 0
      when: ansible_os_family == "Windows"

